linters:
  enable:
    - cyclop # Enables the complexity linter

linters-settings:
  cyclop:
    max-complexity: 10 # Report issues for functions with complexity > 10
    # package-average: 0.0 # You can also set an average complexity for the whole package
